name: 03 - Runners
on: [push]

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar SO
              shell: bash
              run: |
                  echo "Este trabajo se ejecuta en un Runner de Ubuntu" 
                  echo "${{runner.os}}"
    # windows-echo:
    #     runs-on: windows-latest
    #     steps:
    #         - name: Mostrar SO
    #           run: |
    #               echo "Este trabajo se ejecuta en un Runner de Windows" 
    #               echo "${{runner.os}}"
    # mac-echo:
    #     runs-on: macos-latest
    #     steps:
    #         - name: Mostrar SO
    #           run: |
    #               echo "Este trabajo se ejecuta en un Runner MacOS" 
    #               echo "${{runner.os}}"
